#include<stdio.h>
int main()
{
    float reac,asis,tarea,R,x,y,z;
    printf("CUANTOS REACTIVOS SACASTES:\n");//PIDE LOS REACTIVOS QUE OBTUVISTES
    scanf("%f",&reac);//ALMACENA LOS REACTIVOS
    printf("CUANTAS ASISTENCIAS TUVISTES:\n");//PIDE TUS ASISTENCIAS
    scanf("%f",&asis);//ALMACENA LAS ASISTENCIAS
    printf("CUANTAS TAREAS TIENES:\n");	//PIDE TUS TAREAS ENTREGADAS
    scanf("%f",&tarea);	//ALMACENA LAS TAREAS
    x=reac*100/61;//EL REACTIVO SE MULTIPLICA POR 100 Y DESPUES ENTRE 61
    x=x*0.40;//EL RESULTADO OBTENIDO DE X DE MULTIPLICARA POR 0.40
    y=asis*100/7;//TUS ASISTENCIAS SE MULTIPLICA POR 100 Y DESPUES ENTRE 7
    y=y*0.30;//EL RESULTADO OBTENIDO DE Y DE MULTIPLICARA POR 0.30
    z=tarea*100/5;//TUS TAREAS SE MULTIPLICA POR 100 Y DESPUES ENTRE 5
    z=z*0.30;//EL RESULTADO OBTENIDO DE Z DE MULTIPLICARA POR 0.30
    R=x+y+z;//SUMARA LAS TAREAS, ASISTENCIAS Y LOS REACTIVOS DE TU EXAMEN
    printf("TU PROMEDIO ES:%.4f",R);//TE DARA EL PROMEDIO QUE OBTUVISTE,ACORDE A LO QUE ENTREGASTE
    return 0;
}